CONF_TEMP = 'temp'
CONF_HUMIDITY = 'hum'
CONF_DEW_POINT = 'dew'
CONF_PRESSURE = 'pressure'
CONF_NAME = 'name'

KELVIN_CONVERSION = 273.15

AA = 17.62
BB = 243.12

WB_PSY = 0
WB_STULL = 1
WB_DEWPOINT = 2